DROP TABLE IF EXISTS playlist_songs;
DROP TABLE IF EXISTS user_library;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "pgcrypto";
