// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (
  title,
  artist_id,
  cover_image_url,
  release_date
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, artist_id, cover_image_url, release_date, created_at
`

type CreateAlbumParams struct {
	Title         string      `json:"title"`
	ArtistID      uuid.UUID   `json:"artist_id"`
	CoverImageUrl string      `json:"cover_image_url"`
	ReleaseDate   pgtype.Date `json:"release_date"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.Title,
		arg.ArtistID,
		arg.CoverImageUrl,
		arg.ReleaseDate,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.CoverImageUrl,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, title, artist_id, cover_image_url, release_date, created_at
FROM albums
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id uuid.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.CoverImageUrl,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const listAlbumSongs = `-- name: ListAlbumSongs :many
SELECT id, title, album_id, filepath, duration, uploaded_by, created_at
FROM songs
WHERE album_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlbumSongsParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListAlbumSongs(ctx context.Context, arg ListAlbumSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listAlbumSongs, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, title, artist_id, cover_image_url, release_date, created_at
FROM albums
ORDER BY release_date DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlbumsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbums, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.CoverImageUrl,
			&i.ReleaseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtistID = `-- name: ListAlbumsByArtistID :many
SELECT id, title, artist_id, cover_image_url, release_date, created_at
FROM albums
WHERE artist_id = $1
ORDER BY release_date DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlbumsByArtistIDParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAlbumsByArtistID(ctx context.Context, arg ListAlbumsByArtistIDParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByArtistID, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.CoverImageUrl,
			&i.ReleaseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET
  title = $2,
  artist_id = $3,
  cover_image_url = $4,
  release_date = $5
WHERE id = $1
RETURNING id, title, artist_id, cover_image_url, release_date, created_at
`

type UpdateAlbumParams struct {
	ID            uuid.UUID   `json:"id"`
	Title         string      `json:"title"`
	ArtistID      uuid.UUID   `json:"artist_id"`
	CoverImageUrl string      `json:"cover_image_url"`
	ReleaseDate   pgtype.Date `json:"release_date"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.Title,
		arg.ArtistID,
		arg.CoverImageUrl,
		arg.ReleaseDate,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.CoverImageUrl,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}
