// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (
  name,
  slug
) VALUES (
  $1, $2
)
RETURNING id, name, slug, created_at
`

type CreateArtistParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.Name, arg.Slug)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists
WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, slug, created_at
FROM artists
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listArtistAlbums = `-- name: ListArtistAlbums :many
SELECT a.id, a.title, a.artist_id, a.cover_image_url, a.release_date, a.created_at
FROM albums a
WHERE a.artist_id = $1
ORDER BY a.release_date DESC NULLS LAST, a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArtistAlbumsParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListArtistAlbums(ctx context.Context, arg ListArtistAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listArtistAlbums, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.CoverImageUrl,
			&i.ReleaseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistSongs = `-- name: ListArtistSongs :many
SELECT s.id, s.title, s.album_id, s.filepath, s.duration, s.uploaded_by, s.created_at
FROM songs s
JOIN albums a ON a.id = s.album_id
WHERE a.artist_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArtistSongsParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListArtistSongs(ctx context.Context, arg ListArtistSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listArtistSongs, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, slug, created_at
FROM artists
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListArtistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET
  name = $2,
  slug = $3
WHERE id = $1
RETURNING id, name, slug, created_at
`

type UpdateArtistParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist, arg.ID, arg.Name, arg.Slug)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
