// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Playlist struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PlaylistSong struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
	Position   int32     `json:"position"`
}

type Song struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Artist     string    `json:"artist"`
	Filepath   string    `json:"filepath"`
	Duration   int32     `json:"duration"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserLibrary struct {
	UserID  uuid.UUID `json:"user_id"`
	SongID  uuid.UUID `json:"song_id"`
	AddedAt time.Time `json:"added_at"`
}
