// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID            uuid.UUID   `json:"id"`
	Title         string      `json:"title"`
	ArtistID      uuid.UUID   `json:"artist_id"`
	CoverImageUrl string      `json:"cover_image_url"`
	ReleaseDate   pgtype.Date `json:"release_date"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Artist struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type Playlist struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PlaylistSong struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
	Position   int32     `json:"position"`
}

type Song struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	AlbumID    uuid.UUID `json:"album_id"`
	Filepath   string    `json:"filepath"`
	Duration   int32     `json:"duration"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserLibrary struct {
	UserID  uuid.UUID `json:"user_id"`
	SongID  uuid.UUID `json:"song_id"`
	AddedAt time.Time `json:"added_at"`
}
