// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_songs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :one
INSERT INTO playlist_songs (
  playlist_id,
  song_id,
  position
) VALUES (
  $1, $2, $3
)
RETURNING playlist_id, song_id, position
`

type AddSongToPlaylistParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) (PlaylistSong, error) {
	row := q.db.QueryRow(ctx, addSongToPlaylist, arg.PlaylistID, arg.SongID, arg.Position)
	var i PlaylistSong
	err := row.Scan(&i.PlaylistID, &i.SongID, &i.Position)
	return i, err
}

const clearPlaylistSongs = `-- name: ClearPlaylistSongs :exec
DELETE FROM playlist_songs
WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylistSongs(ctx context.Context, playlistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPlaylistSongs, playlistID)
	return err
}

const listPlaylistSongs = `-- name: ListPlaylistSongs :many
SELECT
  ps.playlist_id,
  ps.song_id,
  ps.position,
  s.title,
  s.album_id,
  s.filepath,
  s.duration,
  s.uploaded_by,
  s.created_at
FROM playlist_songs ps
JOIN songs s ON s.id = ps.song_id
WHERE ps.playlist_id = $1
ORDER BY ps.position ASC
LIMIT $2 OFFSET $3
`

type ListPlaylistSongsParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListPlaylistSongsRow struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
	Position   int32     `json:"position"`
	Title      string    `json:"title"`
	AlbumID    uuid.UUID `json:"album_id"`
	Filepath   string    `json:"filepath"`
	Duration   int32     `json:"duration"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListPlaylistSongs(ctx context.Context, arg ListPlaylistSongsParams) ([]ListPlaylistSongsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistSongs, arg.PlaylistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistSongsRow{}
	for rows.Next() {
		var i ListPlaylistSongsRow
		if err := rows.Scan(
			&i.PlaylistID,
			&i.SongID,
			&i.Position,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM playlist_songs
WHERE playlist_id = $1 AND song_id = $2
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SongID)
	return err
}

const updatePlaylistSongPosition = `-- name: UpdatePlaylistSongPosition :one
UPDATE playlist_songs
SET position = $3
WHERE playlist_id = $1 AND song_id = $2
RETURNING playlist_id, song_id, position
`

type UpdatePlaylistSongPositionParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     uuid.UUID `json:"song_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) UpdatePlaylistSongPosition(ctx context.Context, arg UpdatePlaylistSongPositionParams) (PlaylistSong, error) {
	row := q.db.QueryRow(ctx, updatePlaylistSongPosition, arg.PlaylistID, arg.SongID, arg.Position)
	var i PlaylistSong
	err := row.Scan(&i.PlaylistID, &i.SongID, &i.Position)
	return i, err
}
