// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: song.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
  title,
  album_id,
  filepath,
  duration,
  uploaded_by
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, title, album_id, filepath, duration, uploaded_by, created_at
`

type CreateSongParams struct {
	Title      string    `json:"title"`
	AlbumID    uuid.UUID `json:"album_id"`
	Filepath   string    `json:"filepath"`
	Duration   int32     `json:"duration"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Title,
		arg.AlbumID,
		arg.Filepath,
		arg.Duration,
		arg.UploadedBy,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.Filepath,
		&i.Duration,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, title, album_id, filepath, duration, uploaded_by, created_at
FROM songs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSongByID(ctx context.Context, id uuid.UUID) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.Filepath,
		&i.Duration,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, album_id, filepath, duration, uploaded_by, created_at
FROM songs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSongsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByAlbumID = `-- name: ListSongsByAlbumID :many
SELECT id, title, album_id, filepath, duration, uploaded_by, created_at
FROM songs
WHERE album_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSongsByAlbumIDParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListSongsByAlbumID(ctx context.Context, arg ListSongsByAlbumIDParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongsByAlbumID, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET
  title = $2,
  album_id = $3,
  filepath = $4,
  duration = $5
WHERE id = $1
RETURNING id, title, album_id, filepath, duration, uploaded_by, created_at
`

type UpdateSongParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	AlbumID  uuid.UUID `json:"album_id"`
	Filepath string    `json:"filepath"`
	Duration int32     `json:"duration"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.ID,
		arg.Title,
		arg.AlbumID,
		arg.Filepath,
		arg.Duration,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.Filepath,
		&i.Duration,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
