// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_library.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSongToUserLibrary = `-- name: AddSongToUserLibrary :one
INSERT INTO user_library (
  user_id,
  song_id
) VALUES (
  $1, $2
)
RETURNING user_id, song_id, added_at
`

type AddSongToUserLibraryParams struct {
	UserID uuid.UUID `json:"user_id"`
	SongID uuid.UUID `json:"song_id"`
}

func (q *Queries) AddSongToUserLibrary(ctx context.Context, arg AddSongToUserLibraryParams) (UserLibrary, error) {
	row := q.db.QueryRow(ctx, addSongToUserLibrary, arg.UserID, arg.SongID)
	var i UserLibrary
	err := row.Scan(&i.UserID, &i.SongID, &i.AddedAt)
	return i, err
}

const listUserLibrarySongs = `-- name: ListUserLibrarySongs :many
SELECT
  ul.user_id,
  ul.song_id,
  ul.added_at,
  s.title,
  s.album_id,
  s.filepath,
  s.duration,
  s.uploaded_by,
  s.created_at
FROM user_library ul
JOIN songs s ON s.id = ul.song_id
WHERE ul.user_id = $1
ORDER BY ul.added_at DESC
LIMIT $2 OFFSET $3
`

type ListUserLibrarySongsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListUserLibrarySongsRow struct {
	UserID     uuid.UUID `json:"user_id"`
	SongID     uuid.UUID `json:"song_id"`
	AddedAt    time.Time `json:"added_at"`
	Title      string    `json:"title"`
	AlbumID    uuid.UUID `json:"album_id"`
	Filepath   string    `json:"filepath"`
	Duration   int32     `json:"duration"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListUserLibrarySongs(ctx context.Context, arg ListUserLibrarySongsParams) ([]ListUserLibrarySongsRow, error) {
	rows, err := q.db.Query(ctx, listUserLibrarySongs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserLibrarySongsRow{}
	for rows.Next() {
		var i ListUserLibrarySongsRow
		if err := rows.Scan(
			&i.UserID,
			&i.SongID,
			&i.AddedAt,
			&i.Title,
			&i.AlbumID,
			&i.Filepath,
			&i.Duration,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromUserLibrary = `-- name: RemoveSongFromUserLibrary :exec
DELETE FROM user_library
WHERE user_id = $1 AND song_id = $2
`

type RemoveSongFromUserLibraryParams struct {
	UserID uuid.UUID `json:"user_id"`
	SongID uuid.UUID `json:"song_id"`
}

func (q *Queries) RemoveSongFromUserLibrary(ctx context.Context, arg RemoveSongFromUserLibraryParams) error {
	_, err := q.db.Exec(ctx, removeSongFromUserLibrary, arg.UserID, arg.SongID)
	return err
}
